language: c

dist: xenial
services:
  - xvfb
  - docker

env:
  - MINICONDA_DIR=$HOME/miniconda ENVIRONMENT_DIR=$HOME/envs ENVIRONMENT_NAME=test-environment DOCKER_RUN="docker run -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:ro -v $TRAVIS_BUILD_DIR:/opt/mantidimaging" DOCKER_IMAGE="-t dtasev/mantidimaging"

before_install:
  - docker pull dtasev/mantidimaging

jobs:
  include:
    - stage: update-docker-image
      # if: type = cron
      script:
        - cd docker && make build-docker-image

    - stage: test
      script:
        - $DOCKER_RUN $DOCKER_IMAGE flake8
        - $DOCKER_RUN $DOCKER_IMAGE mypy --ignore-missing-imports mantidimaging
        - $DOCKER_RUN $DOCKER_IMAGE nosetests --xunit-file=/opt/result-report.xml

    - stage: upload-nightly
      if: type = cron
      script:
        - $DOCKER_RUN -e GIT_DESCRIBE_NUMBER -e GIT_DESCRIBE_TAG -e UPLOAD_USER -e ANACONDA_API_TOKEN $DOCKER_IMAGE /bin/bash -c "conda config --set anaconda_upload yes && make build-conda-package-nightly"
