language: c

# Makes Travis clone the full repo so that the conda package can get the
# correct string from git describe and correctly label the package
git:
  depth: false

dist: xenial
services:
  - xvfb
  - docker

env:
  >-\n
   MINICONDA_DIR=$HOME/miniconda\n
   ENVIRONMENT_DIR=$HOME/envs\n
   ENVIRONMENT_NAME=test-environment\n
   DOCKER_RUN="docker run -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:ro -v $TRAVIS_BUILD_DIR:/opt/mantidimaging"\n
   DOCKER_IMAGE="-t dtasev/mantidimaging"\n
   ABSEIL_DOCKER_IMAGE="-t dtasev/mantidimaging:abseil"

before_install:
  - docker pull dtasev/mantidimaging

jobs:
  fast_finish: true
  allow_failures:
    - env: CAN_FAIL=true
  include:
    - stage: test
      script:
        - $DOCKER_RUN $DOCKER_IMAGE flake8
        - $DOCKER_RUN $DOCKER_IMAGE mypy --ignore-missing-imports mantidimaging
        - $DOCKER_RUN $DOCKER_IMAGE nosetests

    - stage: upload-nightly
      if: type = cron
      script:
        - $DOCKER_RUN -e UPLOAD_USER -e ANACONDA_API_TOKEN $DOCKER_IMAGE /bin/bash -c "conda config --set anaconda_upload yes && make build-conda-package-nightly"

    - stage: test-abseil
      # if: type = cron # disabled for testing in PR
      env: CAN_FAIL=true
      script:
        - $DOCKER_RUN $ABSEIL_DOCKER_IMAGE flake8
        - $DOCKER_RUN $ABSEIL_DOCKER_IMAGE mypy --ignore-missing-imports mantidimaging
        - $DOCKER_RUN $ABSEIL_DOCKER_IMAGE nosetests