language: c

# Makes Travis clone the full repo so that the conda package can get the
# correct string from git describe and correctly label the package
git:
  depth: false

dist: xenial
services:
  - xvfb
  - docker

env:
  global:
    - MINICONDA_DIR=$HOME/miniconda
    - ENVIRONMENT_DIR=$HOME/envs
    - ENVIRONMENT_NAME=test-environment
    - DOCKER_RUN="docker run -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:ro -v $TRAVIS_BUILD_DIR:/opt/mantidimaging"
  jobs:
    - DOCKER_IMAGE="dtasev/mantidimaging"


before_install:
  - docker pull dtasev/mantidimaging

jobs:
  fast_finish: true
  allow_failures:
    - env: CAN_FAIL=true
  include:
    - stage: test
      name: Test
      script:
        - $DOCKER_RUN -t $DOCKER_IMAGE flake8
        - $DOCKER_RUN -t $DOCKER_IMAGE mypy --ignore-missing-imports mantidimaging
        - $DOCKER_RUN -t $DOCKER_IMAGE nosetests

    - stage: test
      name: Test Abseil
      # if: type = cron # disabled for testing in PR
      env: >-
            CAN_FAIL=true
            DOCKER_IMAGE="dtasev/mantidimaging:abseil"
      script:
        - docker pull $DOCKER_IMAGE
        - $DOCKER_RUN -t $DOCKER_IMAGE flake8
        - $DOCKER_RUN -t $DOCKER_IMAGE mypy --ignore-missing-imports mantidimaging
        - $DOCKER_RUN -t $DOCKER_IMAGE nosetests

    - stage: upload-nightly
      if: type = cron
      script:
        - $DOCKER_RUN -e UPLOAD_USER -e ANACONDA_API_TOKEN -t $DOCKER_IMAGE /bin/bash -c "conda config --set anaconda_upload yes && make build-conda-package-nightly"
