# This is a basic workflow to help you get started with Actions

name: Docker test

on: 
  push:
    branch:
      - add-docker-action
  pull_request:
    branch:
      - add-docker-action
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Pull and run flake8
      run: |
        docker pull dtasev/mantidimaging:latest
        docker run -v $GITHUB_WORKSPACE:/opt/mantidimaging -it dtasev/mantidimaging:latest flake8
