# This is a basic workflow to help you get started with Actions

name: Publish Mantid Imaging docs

inputs:
  token:
    description: 'Github API Token'
    required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
runs:
  using: "composite"

  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
  - name: Make build-env
    shell: bash
    run: python setup.py docs && python setup.py docs_publish