{% set name = 'mantidimaging' %}

  {% set version_tag = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
  {% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}
  {% set version_number = '_' + version_number if version_number != '0' else '' %}

  {% set version = version_tag + version_number %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  git_url: ../

requirements:
  build:
    - python
    - pip
    - setuptools
    - sphinx
  run:
    - python
    - pip
    - astropy
    - scipy
    - scikit-image
    - sharedarray
    - numpy
    # version locked due to v3 being incompatible
    - matplotlib =2.2.3
    - tomopy
    - requests
    - requests-futures
    - python-socketio
    - h5py
    - pyqt
    # version locked due to source changes in mantidimaging/external
    - pyqtgraph =0.10

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
  imports:
    - mantidimaging

app:
  summary: "Mantid Imaging"
  own_environment: True

about:
  home: https://github.com/mantidproject/mantidimaging
  license: GPL-3
  license_file: LICENSE.txt
