name: Testing with (mini)Conda

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: mantidimaging
          environment-file: environment.yml
          python-version: 3.7
          auto-activate-base: false

      - name: Other dependencies
        shell: bash -l {0}
        run: |
          sudo apt update -y
          sudo apt install xvfb x11-utils libxkbcommon-x11-0 -y

      - name: Yapf
        shell: bash -l {0}
        run: |
          yapf --parallel --diff --recursive .

      - name: Flake8
        shell: bash -l {0}
        run: |
          python -m flake8

      - name: mypy
        shell: bash -l {0}
        run: |
          mypy --ignore-missing-imports mantidimaging

      - name: pytest
        env:
          QT_DEBUG_PLUGINS: 1
        shell: bash -l {0}
        run: |
          ulimit -c unlimited
          sudo catchsegv xvfb-run --auto-servernum pytest


