name: Testing with (mini)Conda

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: mantidimaging
          environment-file: environment.yml
          python-version: 3.7
          auto-activate-base: false

      - name: Other dependencies
        shell: bash -l {0}
        run: |
          sudo apt update -y
          sudo apt install xvfb x11-utils libxkbcommon-x11-0 -y

      - name: Yapf
        shell: bash -l {0}
        run: |
          yapf --parallel --diff --recursive .

      - name: Flake8
        shell: bash -l {0}
        run: |
          python -m flake8

      - name: mypy
        shell: bash -l {0}
        run: |
          mypy --ignore-missing-imports mantidimaging

      - name: pytest
        shell: bash -l {0}
        run: |
          ulimit -c unlimited
          ls -la /usr/share/miniconda/condabin
          ls -la /usr/share/miniconda
          ls -la /usr/share/miniconda/bin
          xvfb-run --auto-servernum --server-args="-screen 0 640x480x24" pytest
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          path: /
          # The desired behavior if no files are found using the provided path.

