# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Anaconda repository'
        required: true
        default: 'dtasev'
      home:
        description: 'Label'
        required: false
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Publish Conda
      uses: fcakyon/conda-publish-action@v1.3
      with:
        # Sub-directory with conda recipe
        subdir: $GITHUB_WORKSPACE
        # Anaconda access token
        anacondatoken: ${{ secrets.ANACONDA_API_TOKEN }}
        # Platforms to publish [osx/linux/win]
        platforms: linux
